require 'spec_helper'
require 'byebug'
require 'rspec_html_formatter'
require 'rspec'
require 'input'
require 'rubygems'
require 'bundler/setup'
require 'watir'
require 'DataClientsPage'
require 'AdvancedSearchPage'
require 'DataTransfersPage'
require 'ProjectsPage'
require 'uigen'

