angular.module("ELS")
  .value("projects", [
    {
      projectCode: "H00000",
      matterName: "Test project",
      caseType: "E-Discovery",
      caseDescription: "Test description",
      clientName: "Consilio",
      submittedFor: "Test person",
      dataClientIDs: [1],
      attachments: [
        {
          type: "File",
          fileName: "E:\\Data\\DataFile.Data",
          description: "An attached document",
          public: true,
        },
        {
          type: "Note",
          description: "A useful note",
        },
        {
          type: "Ticket",
          ticketNumber: 234234,
          description: "An attached ticket",
        },
      ],
      history: [
        {
          user: "Test user",
          time: new Date( Date.parse( '1/1/2007' ) ),
          description: "Project description was modified"
        },
        {
          user: "John Doe",
          time: new Date( Date.parse( '1/1/2008' ) ),
          description: "Attachment was added to the project"
        },
      ],
    },
    {
      projectCode: "H00001",
      matterName: "Test project 1",
      caseType: "E-Discovery",
      caseDescription: "The quick brown fox",
      clientName: "Consilio",
      submittedFor: "John Doe",
      dataClientIDs: [2, 3],
      attachments: [],
      history: [],
    },
    {
      projectCode: "H00002",
      matterName: "Test project 2",
      caseType: "E-Discovery",
      caseDescription: "Jumped over the lazy dog",
      clientName: "Enron",
      submittedFor: "Alice Smith",
      dataClientIDs: [0],
      attachments: [],
      history: [],
    },
  ])
  .value("dataClients", [
    {
      clientID: 1,
      projectCodes: ["H00000"],
      clientName: "Data Client Test 1",
    },
    {
      clientID: 2,
      projectCodes: ["H00001"],
      clientName: "Data Client Test 2",
    },
    {
      clientID: 3,
      projectCodes: ["H00001"],
      clientName: "Data Client Test 3",
    },
  ])
  .value("dataTransfers", [
    {
      clientID: 1,
      projectCodes: ["H00000"],
      name: "Data Transfer 1",
    },
    {
      clientID: 2,
      projectCodes: ["H00001"],
      name: "Data Transfer 2",
    },
    {
      clientID: 3,
      projectCodes: ["H00001"],
      name: "Data Transfer 3",
    },
  ])
  .value("savedSearches", [
    {
      name: "Jerry's Checked Out Items",
      criteria: [
        {
          AndOr: "And",
          fieldName: "Current Status",
          value: "OUT",
        },
        {
          AndOr: "And",
          fieldName: "Issued To",
          value: "Jerry",
        },
      ],
    },
    {
      name: "All Hard Drives",
      criteria: [
        {
          AndOr: "And",
          fieldName: "Category",
          value: "Hard Drive - Enclosure",
        },
        {
          AndOr: "Or",
          fieldName: "Category",
          value: "Hard Drive - No enclosure",
        },
      ],
    },
  ])
  .value("itemFields", [
    {
      name: "Item Number",
      locked: true,
      displayInList: true,
      displayInEdit: false,
      required: true,
      type: "number",
    },
    {
      name: "Category",
      locked: true,
      displayInList: true,
      displayInEdit: true,
      required: true,
      type: "multivalue",
      values: [
        "Computer - Laptop",
        "Computer - Desktop",
        "Computer - Server",
        "Hard Drive - Enclosure",
        "Hard Drive - No enclosure",
        "Electronic files",
        "Removable media - CD",
        "Removable media - DVD",
        "Removable media - USB key",
        "Removable media - Backup tape",
        "Removable media - Zip disk",
        "Removable media - Floppy disk",
        "Other",
        "Removable media - Media Card",
      ],
    },
    {
      name: "Make",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: false,
      type: "text",
      dependentOnField: "Category",
      dependentOnValue: "Hard Drive - Enclosure",
    },
    {
      name: "Model",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: false,
      type: "text",
      dependentOnField: "Category",
      dependentOnValue: "Hard Drive - Enclosure",
    },
    {
      name: "Serial Number",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: false,
      type: "text",
      dependentOnField: "Category",
      dependentOnValue: "Hard Drive - Enclosure",
    },
    {
      name: "Source",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: true,
      type: "text",
    },
    {
      name: "Time Received",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: true,
      type: "date",
    },
    {
      name: "Submitted By",
      locked: true,
      displayInList: false,
      displayInEdit: false,
      required: true,
      type: "text",
    },
    {
      name: "Belongs To",
      locked: true,
      displayInList: false,
      displayInEdit: false,
      required: true,
      type: "text",
    },
    {
      name: "Current Status",
      locked: true,
      displayInList: true,
      displayInEdit: false,
      required: true,
      type: "multivalue",
      values: ["IN", "OUT", "Disposed"],
    },
    {
      name: "Issued To",
      locked: true,
      displayInList: false,
      displayInEdit: false,
      required: true,
      type: "text",
    },
    {
      name: "Issued From",
      locked: true,
      displayInList: false,
      displayInEdit: false,
      required: true,
      type: "text",
    },
    {
      name: "Transported By",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: true,
      type: "text",
    },
    {
      name: "Tracking Number",
      locked: true,
      displayInList: true,
      displayInEdit: true,
      required: true,
      type: "number",
    },
    {
      name: "Location",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: false,
      type: "multivalue",
      values: [
        "Huron Legal US - Chicago - Data Intake - Cage room",
        "Huron Legal US - Chicago - Data Intake - Long term storage",
        "Huron Legal US - New York",
        "Huron Legal US - Washington DC",
        "Huron Legal US - San Diego",
        "Huron Legal UK",
      ],
    },
    {
      name: "Send To Lab",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: false,
      type: "boolean",
    },
    {
      name: "Bin Number",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: true,
      type: "number",
    },
    {
      name: "Other Details",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: false,
      type: "longText",
    },
    {
      name: "Sender Description",
      locked: true,
      displayInList: false,
      displayInEdit: true,
      required: false,
      type: "longText",
    },
  ])
  .value("items", [
    {
      'Item Number': 1,
      'Submitted By': "Test person",
      'Belongs To': "Test person",
      'Current Status': "IN",
      'Category': "Computer - Laptop",
      'Issued To': "Test person",
      'Issued From': "Test person",
      'Time Received': new Date( Date.parse( '1/1/2005' ) ),
      'Transported By': "Test person",
      'Tracking Number': 428293,
      'Location': "Huron Legal US - Chicago - Data Intake - Cage room",
      'Send To Lab': false,
      'Bin Number': 298,
      'Other Details': "Test details",
      'Source': "Test source data",
      'Sender Description': "Test description",
      projectCode: 'H00000',
      dataClientID: 1,
      dataTransferID: 1,
      attachments: [
        {
          type: "Note",
          description: "Item note",
        },
        {
          type: "File",
          fileName: "E:\\Data\\DataFile.Data",
          description: "An attached document",
          public: true,
        },
        {
          type: "Note",
          description: "A useful note",
        },
        {
          type: "Ticket",
          ticketNumber: 234234,
          description: "An attached ticket",
        },
      ],
      history: [
        {
          user: "Test user",
          time: new Date( Date.parse( '1/1/2007' ) ),
          description: "Item field was modified"
        },
        {
          user: "John Doe",
          time: new Date( Date.parse( '1/1/2008' ) ),
          description: "Attachment was added to the item"
        },
      ],
    },
    {
      'Item Number': 2,
      'Submitted By': "Test person",
      'Belongs To': "Test person",
      'Current Status': "IN",
      'Category': "Removable media - CD",
      'Issued To': "Test person",
      'Issued From': "Test person",
      'Time Received': new Date( Date.parse( '1/1/2007' ) ),
      'Transported By': "Test person",
      'Tracking Number': 4353,
      'Location': "Huron Legal US - Chicago - Data Intake - Long term storage",
      'Send To Lab': false,
      'Bin Number': 298,
      'Other Details': "Test details",
      'Source': "Test source data",
      'Sender Description': "Test description",
      projectCode: 'H00000',
      dataClientID: 1,
      dataTransferID: 1,
      attachments: [],
      history: [],
    },
  ])
