source 'https://rubygems.org'

gem 'rake', '>= 10.4.2'
gem 'rubocop', '>= 0.34.2'

# vra driver gems
gem 'kitchen-vra', '>= 1.1.0'
gem 'kitchen-vagrant', '>= 0.19.0'

# test-kitchen gems
gem 'test-kitchen', '~> 1.5.0'
gem 'winrm', '~> 1.5.0'
gem 'winrm-transport', '~> 1.0.3'
gem 'winrm-s', '~> 0.3.4'
