name 'relativity-scaled-automation-sri'
maintainer 'Consilio, LLC'
maintainer_email 'kxmoss@consilio.com'
license 'all_rights'
description 'Installs/Configures relativity-scaled-automation-sri'
long_description 'Installs/Configures relativity-scaled-automation-sri'
version '2.0.0'
depends 'dotnet', '~> 2.1.3'
depends 'dotnetframework', '~> 1.2.0'
depends 'msoffice', '~> 0.1.0'
depends 'seven_zip', '~> 1.2.3'
depends 'windows', '~> 1.39.1'
depends 'iis', '~> 4.1.6'
depends 'sqlserver', '~> 3.1.4'
depends 'firewall', '~> 2.5.0'
