//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Container()
        {
            this.ContainerBusinessProjectMappings = new HashSet<ContainerBusinessProjectMapping>();
            this.Custodies = new HashSet<Custody>();
            this.ParentContainer = new HashSet<Container>();
        }
    
        public long Id { get; set; }
        public bool IsPhysical { get; set; }
        public bool IsLogical { get; set; }
        public int ContainerTypeId { get; set; }
        public string ContainerTypeName { get; set; }
        public Nullable<int> ContainerSubtypeId { get; set; }
        public string ContainerSubTypeName { get; set; }
        public Nullable<int> DataClientId { get; set; }
        public long DataTransferId { get; set; }
        public string DataTransferName { get; set; }
        public Nullable<long> ParentContainerId { get; set; }
        public int DispositionStateId { get; set; }
        public string DispositionStateName { get; set; }
        public string Description { get; set; }
        public string Password { get; set; }
        public long HistoricUid { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual DispositionState DispositionState { get; set; }
        public virtual ContainerSubtype ContainerSubtype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContainerBusinessProjectMapping> ContainerBusinessProjectMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custody> Custodies { get; set; }
        public virtual ContainerType ContainerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Container> ParentContainer { get; set; }
        public virtual DataTransfer DataTransfer { get; set; }
    }
}
