//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContainerBusinessProjectMapping
    {
        public long Id { get; set; }
        public long ContainerId { get; set; }
        public int BusinessProjectId { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public int Deleted { get; set; }
        public int DeletedBy { get; set; }
    
        public virtual Container Container { get; set; }
    }
}
