//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custody
    {
        public long Id { get; set; }
        public long ContainerId { get; set; }
        public Nullable<int> FromEvidenceHandlerId { get; set; }
        public string FromEvidenceHandlerDisplayName { get; set; }
        public int TransferredByEvidenceHandlerId { get; set; }
        public string TransferredByEvidenceHandlerDisplayName { get; set; }
        public System.DateTime TransferDatetime { get; set; }
        public int ReasonForTransferId { get; set; }
        public string ReasonForTransferName { get; set; }
        public int NewEvidenceLocationId { get; set; }
        public string NewEvidenceLocationName { get; set; }
        public string ServiceTicketNumber { get; set; }
        public string Notes { get; set; }
        public long HistoricUid { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual EvidenceHandler FromEvidenceHandler { get; set; }
        public virtual EvidenceHandler TransferredByEvidenceHandler { get; set; }
        public virtual ReasonForTransfer ReasonForTransfer { get; set; }
        public virtual EvidenceLocation EvidenceLocation { get; set; }
    }
}
