//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTransfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataTransfer()
        {
            this.Containers = new HashSet<Container>();
        }
    
        public long Id { get; set; }
        public int DataTransferTypeId { get; set; }
        public string DataTransferTypeName { get; set; }
        public Nullable<int> DataClientId { get; set; }
        public int BusinessProjectId { get; set; }
        public Nullable<int> CampusId { get; set; }
        public System.DateTime DataTransferDatetime { get; set; }
        public int CollectingEvidenceHandlerId { get; set; }
        public string CollectingEvidenceHandlerDisplayName { get; set; }
        public Nullable<int> DeliveringEvidenceHandlerId { get; set; }
        public string DeliveringEvidenceHandlerDisplayName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TrackingNumber { get; set; }
        public long HistoricUid { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual DataTransferType DataTransferType { get; set; }
        public virtual EvidenceHandler DataTransferCollectingEvidenceHandler { get; set; }
        public virtual EvidenceHandler DataTransferDeliveringEvidenceHandler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Container> Containers { get; set; }
    }
}
