//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvidenceHandler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvidenceHandler()
        {
            this.DataTransfersCollectingEvidenceHandler = new HashSet<DataTransfer>();
            this.DataTransfersDeliveringEvidenceHandler = new HashSet<DataTransfer>();
            this.CustodiesFromEvidenceHandler = new HashSet<Custody>();
            this.CustodiesTransferredByEvidenceHandler = new HashSet<Custody>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserIdentifier { get; set; }
        public string DisplayName { get; set; }
        public long HistoricUid { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataTransfer> DataTransfersCollectingEvidenceHandler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataTransfer> DataTransfersDeliveringEvidenceHandler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custody> CustodiesFromEvidenceHandler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custody> CustodiesTransferredByEvidenceHandler { get; set; }
    }
}
